### ISSUE TITLE
Is it possible to retrieve ligand information for an individual ligand using the API?

### ISSUE THREAD

**Issue by syedzayyan** [protwis/gpcrdb_data#136]
Hello All,

Basically the title.

for each ligand, there is a [page](https://gpcrdb.org/ligand/4077/info). I was wondering if it was possible to search using the API like that.

**Comment by pszgaspar** [comment]
Hi,

We don't yet have an API call that gives that detailed of an information of a given ligand, though we could implement something like that. We will look into it, thanks for reaching out.

Best,
Gaspar
