### ISSUE TITLE
What does the cs.tsv contain?

### ISSUE THREAD

**Issue by YojanaGadiya** [protwis/gpcrdb_data#150]
Dear GPCRdb team,

We are looking at this specific file named [cs.tv](https://github.com/protwis/gpcrdb_data/blob/master/structure_data/cs.tsv) in your repo and are unable to understand what this subset of proteins is and what the count is 130 only where there are more than 1000 GPCR proteins in the other folder. Please could you explain a bit on how this subsetting was done?

Regards,
Yojana gadiya

**Comment by pszgaspar** [comment]
Hi Yojana,
This is an old file which we don't use anymore, it got left in the repo by accident. It was a file for containing information of published structures, which at that time (9 years ago) was 130. If you are looking for up to date structural information, look at the .csv files in the annotation folder.
Best,
Gaspar

**Comment by YojanaGadiya** [comment]
Thank you @pszgaspar. This helps. One follow-up question from our end:

We are trying to find a subset of ligand-bound GPCRs and a file(s) that summarizes the PDB IDs and metadata for these GPCRs. Do you think we should refer to any specific file in the annotation that can help us get this information?

Regards,
Yojana Gadiya

**Comment by pszgaspar** [comment]
The GPCRdb_structure_info.xlsx has everything on structures. The different tabs in that file get parsed into separate csv files. The structures.csv has general info on the structure, ligands.csv has info on the ligands in the structure, g_proteins.csv and arrestins.csv store info on coupled signaling proteins and we also have grk.csv, ramp.csv, nanobodies.csv and fusion_proteins.csv. All of these have the pdb id as identifier, the structures.csv has the receptor UniProt entry name.

**Comment by pszgaspar** [comment]
And FYI, I am updating these files with 100+ structures in the upcoming days

**Comment by YojanaGadiya** [comment]
Oh great! I shall then wait for your updates :) Thank you so much for your quick responses.

**Comment by pszgaspar** [comment]
I checked and actually had everything already prepared so the update is online. It is in #151
